### ISSUE TITLE
Cannot proceed while signing in when telemetry is disabled modules config

### ISSUE THREAD

**Issue by xegim** [element-hq/element-x-android#4359]
### Steps to reproduce

1. Disable the analytics in [ModulesConfig.kt](https://github.com/element-hq/element-x-android/blob/develop/plugins/src/main/kotlin/ModulesConfig.kt) [by setting](https://github.com/element-hq/element-x-android/blob/0d1a35970d54929feaaa7db249b48ee60137e953/plugins/src/main/kotlin/ModulesConfig.kt#L17C44-L17C67) `analyticsConfig` to `AnalyticsConfig.Disabled`.
2. Install and clear the application data for a fresh start
3. Follow the sign in steps and try to proceed after "enable notifications" view

#### What did you expect?
Chat view to open without going through the analytics opt in view. It should be possible to remove the telemetry entirely in custom builds by utilizing the module config without breaking other things.

#### What happened instead?
The app does not proceed after enable notifications view (either by selecting allow or "not now"). The app needs to be restarted in order to proceed to chats.

### Your phone model

Sony Xperia V III / Samsung Galaxy Tab S9 FE

### Operating system version

13

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by bmarty** [comment]
We fixed this issue in a pretty old pr (https://github.com/element-hq/element-x-android/pull/3337). Are you up to date? If not please get the latest upstream code.
If yes, the issue is back. Please let us know!
CC @SpiritCroc

**Comment by SpiritCroc** [comment]
Signing in was working for me on SchildiChat Next based on 25.09.2, not sure if I tested on 25.10.0 yet but if then it was still working as well.

From my commit history, if I don't miss anything last time I had to fix it was https://github.com/SchildiChat/schildichat-android-next/commit/3af519fa4ee203477578c50fc75a82c3ee7306f6
Checking a git diff, I actually still have

```
diff --git a/features/ftue/impl/src/main/kotlin/io/element/android/features/ftue/impl/state/DefaultFtueService.kt b/features/ftue/impl/src/main/kotlin/io/element/android/features/ftue/impl/state/DefaultFtueService.kt
index 40f19b1e7a..ec9987fc6d 100644
--- a/features/ftue/impl/src/main/kotlin/io/element/android/features/ftue/impl/state/DefaultFtueService.kt
+++ b/features/ftue/impl/src/main/kotlin/io/element/android/features/ftue/impl/state/DefaultFtueService.kt
@@ -109,7 +109,10 @@ class DefaultFtueService(
             } else {
                 getNextStep(FtueStep.AnalyticsOptIn)
             }
-            FtueStep.AnalyticsOptIn -> null
+            FtueStep.AnalyticsOptIn -> {
+                ftueStepStateFlow.emit(InternalFtueState.Complete) // SC: fix login flow getting stuck, again...
+                null
+            }
         }

     private fun isSessionVerificationStateReady(): Boolean {
```

I probably forgot to re-test against upstream at some point, so could be that's necessary (I'm happy to PR and/or providing sign-off if required). Not sure if this messes with the login flow when having analytics enabled.

**Comment by bmarty** [comment]
Thanks for the fast reply @SpiritCroc.

I have checked again by just setting `val analyticsConfig: AnalyticsConfig = AnalyticsConfig.Disabled` in the  configuration file and I do not reproduce the issue.

@xegim can you try again using the latest upstream code please? There have been recent change in this area and the issue is probably fixed now. If this is not the case, please let me know.

Thanks!

**Comment by xegim** [comment]
Thanks a lot for having a look! I'm not able to test right now, but will do so later with the latest code and report here if I still have issues with it.
